xarray-contrib/xeofs

xeofs/xarray/eof.py
xeofs/xarray/mca.py
xeofs/xarray/rock_pca.py

One more small one. When supplying a custom array to `weights` in the `xarray` interface, we get:
```
FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
use_coslat = True if weights == 'coslat' else False
```
This just checks if `weights` is a `str` before trying to compare so we don't get the warning.

fix: FutureWarning in coslat check

---

xeofs/utils/xarray_utils.py

- padding was not always performed along the specified dimensions, this was corrected by fixing the input and output core dimensions to `sample` and `feature`
- missing to recenter the data after Hilbert transform with padding sometimes led to biases which resulted in incorrect patterns/scores; this only affected complex (Hilbert) variants.

fix: correct bias in Hilbert trans when padding

---

tests/models/test_complex_mca.py
tests/models/test_complex_mca_rotator.py
tests/models/test_mca.py
xeofs/models/decomposer.py
xeofs/models/mca.py
xeofs/models/mca_rotator.py

- fix erroneous dot product when computing scores (closes #65 ) credits to @mschulzie
- add conjugate when computing total squared covariance in CrossDecomposer (closes #64 ) @mschulzie
- streamline covariance and squared covariance fraction for MCA

fix: correct MCA scores and SCF

---

pyproject.toml

last release did not trigger PSR action to publish to PyPI. Therefore version number lags behid the release number. To resolve PSR error bump version by hand.

chore(release): bump version

---

docs/environment.yml

Include ipykernel in the doc environment which is required to build documentation on readthedocs

build: add ipykernel as dependency

---

xeofs/models/_base_cross_model.py
xeofs/models/_base_model.py

Closes #106. Figured this was clearer than directly passing through a default `mode` kwarg, since I can't imagine ever wanting to use 'a' or 'r+' here.

fix: safe default zarr write mode

---

poetry.lock
pyproject.toml

poetry.groups are not installed by pip. This fix adds
xarray-datatree to the main dependency group in
pyproject.toml (fixes #112)

fix: remove xarray-datatree from poetry.group

---

xeofs/models/eof_rotator.py
xeofs/models/mca_rotator.py

I was having trouble round-tripping properly when doing things in lazy mode without explicitly calling `.compute()`. Realized it was because in `transform()` the modes were getting sorted by variance regardless of whether the model itself was sorted.

fix: only sort transform if model is already sorted

---

tests/models/test_eof.py
tests/models/test_eof_rotator.py
tests/models/test_mca.py
tests/models/test_mca_rotator.py
xeofs/models/_base_cross_model.py
xeofs/models/_base_model.py
xeofs/utils/io.py

Realized it's actually pretty easy to add support for netcdf serialization, despite the limitations on dtypes for attrs. We can just intelligently convert non-supported types to and from strings. Seemed worth adding this option since the DataTree zarr backend has some issues currently (e.g. [#277](https://github.com/xarray-contrib/datatree/issues/277)) and may be getting a rework eventually. I did leave the default as zarr.

feat: support saving to netcdf

---

tests/models/test_eof.py
tests/models/test_eof_rotator.py
tests/models/test_mca.py
tests/models/test_mca_rotator.py
tests/models/test_orthogonality.py
xeofs/models/_base_model.py
xeofs/models/mca_rotator.py

Small change to allow passing either normalized or raw scores through `inverse_transform` in the public API. Previously you would need to work with the raw scores, e.g.:
```python
scores = model.scores(normalized=False)
data_recon = model.inverse_transform(scores)
```
to get proper roundtripping behavior, and it took me a little digging to figure this out. Now we can do:
```python
scores = model.scores(normalized=False)
data_recon = model.inverse_transform(scores, normalized=False)
scores = model.scores(normalized=True)
data_recon = model.inverse_transform(scores, normalized=True)
```
and get a good reconstruction.
Note this is only on the EOF-based models for now. I started trying to implement the `normalized` option across the MCA family of models as well, but couldn't get the …

feat: normalized option in inverse_transform

---

.github/workflows/release_package.yml

Based on the most recent note on your issue @nicrie ([#654](https://github.com/python-semantic-release/python-semantic-release/issues/654#issuecomment-1736850729)) and the [migration guide](https://python-semantic-release.readthedocs.io/en/latest/migrating_from_v7.html), I think this might fix the first item of #126.

fix: update to handle v8 semantic release GH action

---

docs/overview_2_features.rst

Looks like the performance tests link was broken.
JOSS review: https://github.com/openjournals/joss-reviews/issues/6060

docs: fix link to perf scripts

---

tests/models/test_eof.py
tests/models/test_eof_rotator.py
tests/models/test_mca.py
tests/models/test_mca_rotator.py
xeofs/preprocessing/transformer.py

Serialize/deserialize weren't working properly for the preprocessor transformers when passed a `Dataset`. This seems to fix the immediate issue in #135. I want to add new tests though and dig a bit deeper.

fix: serialization for dataset

---

.github/workflows/ci.yml
README.md

Instead of using simple code snippets in `README` use `doctest` to ensure that shown examples are actually working (part of #130)

docs: use doctest to test README examples

---

xeofs/models/cca.py

Previously, the explained (co)variance in PCA-CCA was computed with respect to the pre-processed PCA views. Fixed by using the actual (non-PCA) data (see #146)

fix: incorrect explained variance in CCA

---

tests/models/test_eof.py
tests/models/test_opa.py
xeofs/models/_base_model.py
xeofs/models/eof.py

Reconstructing the original data via 'inverse_transform' fails when a single mode is used with normalized PCs. Explicilty select the number of modes of the L2 norms to avoid incorrect broadcasting.
resolves #149

fix: inverse_transform fails with single mode and normalized pcs

---

pyproject.toml

Found one small issue in the `build_command`, which is that we need to `pip install build` to get it to work in the GH Action.

build: install build in semantic release

---

CHANGELOG.md
cliff.toml

This PR removes the release commits from the CHANGELOG file. In the past, we used two different styles of commit messages when making a new release. PR #141 covered one of them, here we cover the other style.

docs: Remove release commits from CHANGELOG

---

tests/models/test_complex_eof_rotator.py
tests/models/test_decomposer.py
tests/models/test_eof_rotator.py
xeofs/data_container/data_container.py
xeofs/models/_base_cross_model.py
xeofs/models/_base_model.py
xeofs/preprocessing/preprocessor.py
xeofs/preprocessing/transformer.py
xeofs/utils/io.py

`datatree` is about to be merged into the public API of `xarray`. This adds a preferential import for the native `xarray` version but leaves the archived `xarray-datatree` package as a dependency, because it is small and avoids complications with supporting older xarray versions.
Also adds support for `numpy==2.0` with a couple very small fixes.

fix: support new datatree and numpy 2.0

---

tests/preprocessing/test_pca_preprocessor_dataarray.py
xeofs/preprocessing/pca_preprocessor.py
xeofs/preprocessing/preprocessor.py

This PR introduces a `PCAPreprocessor` class for transforming input data into a whitened, rank-reduced PCA space. It’s useful for cross models, enabling dimensionality reduction before extracting common patterns. This class is a key component of Continuum Power CCA (see #178).

refactor: add `PCAPreprocessor` class

---

tests/preprocessing/test_whitener.py
xeofs/preprocessing/whitener.py
xeofs/utils/linalg.py

Prior to this PR, the `Whitener` class could only whiten the data using PCA. This PR extends the `Whitener` class by two additional working modes:
1. Whitening without PCA
2. Identify transformation (thus no whitening, no PCA transformation) for `alpha=1` and `use_pca=False`

refactor(whitener): add more flexibility

---

xeofs/preprocessing/sanitizer.py

Replace class method `self._check_input_type()` with general utility function `assert_single_dataarray`

refactor(sanitizer): reuse utility function to test input types

---

xeofs/data_container/data_container.py

This PR includes a refactoring of the `DataContainer` module to allow for the serialization of parameter lists. The changes ensure that boolean and None values are converted to strings when validating attributes, even when they are present within a list.

refactor(datacontainer): parameter list serialization

---

xeofs/models/_base_cross_model.py
xeofs/models/_base_model.py

chore: add deprecation warning for verbose parameter

---

docs/api_reference/multi_set_analysis.rst
docs/api_reference/single_set_analysis.rst
examples/1single/plot_complex_eof.py
tests/models/test_complex_eof.py
tests/models/test_complex_eof_rotator.py
tests/models/test_complex_mca.py
tests/models/test_complex_mca_rotator.py
tests/models/test_orthogonality.py
tests/models/test_rotator.py
xeofs/models/__init__.py
xeofs/models/eof.py
xeofs/models/eof_rotator.py
xeofs/models/mca.py
xeofs/models/mca_rotator.py
xeofs/models/rotator_factory.py

With the upcoming release v3.0 in mind, this deprecation warning is intended to prepare users for the renaming of the `Complex` classes (#188 ).

fix: add deprecation warning for `Complex` model classes

---

xeofs/models/_base_model_cross_set.py
xeofs/models/_base_model_single_set.py
xeofs/models/cpcca_rotator.py
xeofs/models/eof.py
xeofs/models/sparse_pca.py

For `scores` switch from `True` to `False` to align more closely with the scikit-learn convention. For `components`, keep `True`.

feat: change default value of parameter `normalized`

---

xeofs/data_container/data_container.py
xeofs/models/cca.py
xeofs/models/cpcca.py
xeofs/models/cpcca_rotator.py
xeofs/models/eeof.py
xeofs/models/eof.py
xeofs/models/eof_rotator.py
xeofs/models/opa.py
xeofs/models/sparse_pca.py
xeofs/preprocessing/concatenator.py
xeofs/preprocessing/dimension_renamer.py
xeofs/preprocessing/list_processor.py
xeofs/preprocessing/multi_index_converter.py
xeofs/preprocessing/preprocessor.py
xeofs/preprocessing/sanitizer.py
xeofs/preprocessing/scaler.py
xeofs/preprocessing/stacker.py
xeofs/preprocessing/transformer.py
xeofs/preprocessing/whitener.py
xeofs/utils/data_types.py
xeofs/utils/xarray_utils.py
xeofs/validation/bootstrapper.py

Replaced typing.Dict, List, Tuple, and Optional with the built-in types
dict, list, tuple, and None as per Python 3.10+ syntax.

refactor(typing): use built-in types for annotations

---

xeofs/cross/cca.py

This PR sets `alpha=0.0` in the `HilbertCCA`. Before it was accidentally set to `alpha=1`.

fix: alpha paramter in Hilbert CCA

---

xeofs/cross/cpcca.py

Before, we computed the TSC in the original (physical) space which required computing a large covariance matrix. As a result, we ran out of memory even for datasets of moderate size. Now we compute the TSC in PC space.

fix(cross): compute total squared covariance in PC space

---

xeofs/cross/base_model_cross_set.py
xeofs/cross/cpcca.py

This fix solves some regressions introduced in v3 for the cross-set classes:
- Hilbert cross-set models did not transform `Y` data correctly ([960f744](https://github.com/xarray-contrib/xeofs/pull/223/commits/960f74429a01d614bd9289d762550128206330a0)) (close #219)
- Total squared covariance was computed in physical rather than PC space resulting in unnecessary memory consumption ([2dd3e86](https://github.com/xarray-contrib/xeofs/pull/223/commits/2dd3e86d1b41416346a31c6dffd261834990426b)) (close #220)

chore(release): 3.0.1

---

xeofs/base_model.py
xeofs/data_container/data_container.py
xeofs/preprocessing/preprocessor.py
xeofs/preprocessing/transformer.py

closes #226 
Lot's of changes to datatree on xarray main since the latest release. These 3 all tripped us up:
https://github.com/pydata/xarray/pull/9297
https://github.com/pydata/xarray/pull/9444
https://github.com/pydata/xarray/pull/9476
Maybe it was a little early to [enable](https://github.com/xarray-contrib/xeofs/pull/169) using the migrated datatree since it's not technically public API yet but I suppose it let's us fix these issues quickly.

fix: xarray 2024.09.0 compatility

---

tests/models/cross/test_cpcca.py
tests/models/cross/test_hilbert_cpcca.py
tests/models/cross/test_hilbert_mca_rotator.py
xeofs/cross/base_model_cross_set.py
xeofs/cross/cpcca.py
xeofs/cross/cpcca_rotator.py

Add `sample_name` and `feature_name` to the serialization attributes of `CPCCA` and `CPCCARotator` models which are needed for some methods (e.g. `squared_covariance_fraction()`). 
Additionally, fix a bug that resulted in an error when `components_amplitude()` was called on a saved model which was loaded lazily.
Closes #224

fix(cross): correct saving and loading of CPCCA and Rotator models

---

tests/models/cross/test_hilbert_mca_rotator.py
tests/models/cross/test_mca_rotator.py
tests/models/single/test_eof_rotator.py
tests/models/single/test_hilbert_eof_rotator.py
xeofs/cross/cpcca_rotator.py
xeofs/cross/mca_rotator.py
xeofs/single/eof_rotator.py

This PR improves disk space efficiency when saving the `Rotator`. Previously, the entire model, including its `Preprocessor` and `Whitener`, was saved twice -- once for the original model and once for the Rotator. This resulted in redundant storage, particularly for the `Whitener`, which can be large due to its transformation matrix.
To address this, the PR no longer saves the entire original model. Instead, it creates a `DataContainer` for the original model and only copies the necessary `DataArrays` required by the Rotator, avoiding duplicate data.

perf: avoid redundant data when saving Rotator models

---

xeofs/linalg/_numpy/_rotation.py

Move some computations in front of the loop and use broadcasting instead of matrix multiplication. I ran some tests that showed an improved performance of about 20 % on average. I also tried numba but that did not bring any significant gains.

perf: speed up rotation by about 20%

---

tests/models/cross/test_hilbert_cpcca.py
tests/models/single/test_pop.py
tests/preprocessing/test_pca.py
tests/preprocessing/test_whitener.py
xeofs/cross/base_model_cross_set.py
xeofs/cross/cpcca.py
xeofs/cross/cpcca_rotator.py
xeofs/preprocessing/__init__.py
xeofs/preprocessing/pca.py
xeofs/preprocessing/whitener.py
xeofs/single/pop.py

During the data preprocessing of the Hilbert CPCCA model the data was first whitened and then Hilbert transformed. The final Hilbert transform destroyed the whitening property of the data. The correct order should be Hilbert transform -> Whitening. 
In order to fix this we refactor the `Whitener` into two classes, a `PCA` preprocessor and a pure `Whitener`. Then we move the data augmentation step in between the `PCA` and `Whitener` step.

fix: correct whitening in HilbertCPCCA models

---

pyproject.toml
xeofs/base_model.py
xeofs/data_container/data_container.py
xeofs/preprocessing/preprocessor.py
xeofs/preprocessing/transformer.py
xeofs/utils/io.py

[xarray==2024.10.0](https://docs.xarray.dev/en/stable/whats-new.html#v2024-10-0-oct-24th-2024) now has `DataTree` as public API, and the old prototype library has been [archived](https://github.com/xarray-contrib/datatree).
The modifications here drop support for the archived version and ensure everything works on the new version that's available in xarray. Only downside is we have to bump the lower bound on xarray support all the way up to present.

fix: support new datatree
